###
POST http://localhost:8080/v1/posts
Content-Type: application/json

{
  "author": "test author",
  "password": "1234",
  "title": "is this title?",
  "content": "is this content??"
}

###
GET http://localhost:8080/v1/posts/2

###
DELETE http://localhost:8080/v1/posts/1
Content-Type: application/json

{
  "author": "test author",
  "password": "1234"
}

###
PATCH http://localhost:8080/v1/posts/2
Content-Type: application/json

{
  "author": "test author2",
  "password": "456",
  "title": "게시판인가요?2",
  "content": "이건 내용인가요?2"
}


###
POST http://localhost:8080/v1/comments
Content-Type: application/json

{
  "author": "comment author",
  "password": "456",
  "postSeq": 1,
  "content": "2댓글입니당2"
}
