app:
  url: http://localhost:8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true


logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

